import { StyleSheet } from 'react-native'
import { colors, typography } from '../../utils/globalStyle'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.honeydew,
    width: '100%',
  },
  headerSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.caribbeanGreen,
    width: '100%',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerContent: {
    paddingTop: 30,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerTitle: {
    ...typography.titleBold,
    fontSize: 24,
    color: colors.void,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryCard: {
    backgroundColor: colors.caribbeanGreen,
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    height: 160,
    elevation: 3,
  },
  summaryItem: {
    flex: 1,
  },
  progressContainerWrapper: {
    alignItems: 'center',
    marginBottom: 12,
  },
  circularProgressOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 8,
    overflow: 'hidden',
  },
  progressArcContainer: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  progressArc1: {
    position: 'absolute',
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: colors.caribbeanGreen,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
    top: 0,
    left: 0,
  },
  progressArc2: {
    position: 'absolute',
    width: 76,
    height: 38,
    backgroundColor: colors.caribbeanGreen,
    top: 0,
    left: 0,
    borderTopLeftRadius: 38,
    borderTopRightRadius: 38,
  },
  circularProgressInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  savingsTextContainer: {
    alignItems: 'center',
    marginTop: -15,
  },
  savingsTextLine1: {
    ...typography.bodyMedium,
    fontSize: 12,
    color: colors.void,
    fontWeight: '500',
  },
  savingsTextLine2: {
    ...typography.bodyMedium,
    fontSize: 12,
    color: colors.void,
    fontWeight: '500',
  },
  summaryDivider: {
    width: 1,
    height: 200,
    backgroundColor: '#FFFFFF',
    opacity: 0.3,
    marginHorizontal: 16,
    marginTop: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  summaryRowDivider: {
    width: '80%',
    height: 1,
    backgroundColor: '#FFFFFF',
    opacity: 0.3,
    marginLeft: 32,
  },
  summaryDetails: {
    marginLeft: 12,
    flex: 1,
  },
  summaryLabelWhite: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.void,
    fontWeight: '400',
  },
  summaryAmountWhite: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
    marginTop: 4,
  },
  summaryAmountBlue: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.oceanBlue,
    fontWeight: 'bold',
    marginTop: 4,
  },
  scrollableContent: {
    flex: 1,
    paddingTop: 240,
  },
  contentBackground: {
    flex: 1,
    backgroundColor: colors.honeydew,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  chartSection: {
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  chartTitle: {
    ...typography.titleBold,
    fontSize: 20,
    color: colors.void,
    fontWeight: 'bold',
  },
  chartHeaderIcons: {
    flexDirection: 'row',
    gap: 12,
  },
  chartIconButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chartContainer: {
    flexDirection: 'row',
    height: 200,
    backgroundColor: colors.lightGreen,
    borderRadius: 16,
    padding: 16,
  },
  yAxisLabels: {
    justifyContent: 'space-between',
    paddingRight: 8,
    height: '100%',
  },
  yAxisLabel: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.cyprus,
    opacity: 0.6,
  },
  barsContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    paddingLeft: 8,
  },
  weekColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: '100%',
  },
  barsWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    marginBottom: 8,
    height: 160,
  },
  bar: {
    width: 16,
    backgroundColor: colors.caribbeanGreen,
    borderRadius: 4,
    minHeight: 20,
  },
  barGreen: {
    backgroundColor: colors.caribbeanGreen,
  },
  barBlue: {
    backgroundColor: colors.vividBlue,
  },
  weekLabel: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.cyprus,
    opacity: 0.8,
    marginTop: 4,
  },
  transactionsContainer: {
    paddingHorizontal: 24,
  },
  transactionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGreen,
  },
  transactionIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.lightBlue,
    opacity: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  transactionDetails: {
    flex: 1,
  },
  transactionName: {
    ...typography.bodyLarge,
    fontSize: 16,
    color: colors.void,
    fontWeight: '600',
    marginBottom: 4,
  },
  transactionMeta: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.vividBlue,
    opacity: 0.8,
    marginBottom: 2,
  },
  transactionCategory: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.cyprus,
    opacity: 0.8,
  },
  transactionAmountPositive: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
  },
  transactionAmountNegative: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
})

