import { StyleSheet } from 'react-native'
import { colors, typography } from '../../utils/globalStyle'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.honeydew,
    width: '100%',
  },
  headerSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.caribbeanGreen,
    width: '100%',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerContent: {
    paddingTop: 20,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerTitle: {
    ...typography.titleBold,
    fontSize: 24,
    color: colors.void,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  totalBalanceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalBalanceLabel: {
    ...typography.bodySmall,
    fontSize: 14,
    color: colors.cyprus,
    opacity: 0.7,
    marginBottom: 8,
  },
  totalBalanceAmount: {
    ...typography.titleBold,
    fontSize: 32,
    color: colors.void,
    fontWeight: 'bold',
  },
  financialSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  balanceContainer: {
    flex: 1,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  balanceLabel: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 4,
    opacity: 0.8,
  },
  balanceAmount: {
    ...typography.titleBold,
    fontSize: 22,
    color: colors.void,
    fontWeight: 'bold',
  },
  divider: {
    width: 1,
    backgroundColor: '#FFFFFF',
    opacity: 0.2,
    marginHorizontal: 16,
  },
  expenseContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  expenseLabel: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 4,
    opacity: 0.8,
  },
  expenseAmount: {
    ...typography.titleBold,
    fontSize: 22,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
  progressContainer: {
    marginTop: 8,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressBar: {
    flex: 1,
    height: 27,
    backgroundColor: colors.void,
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'row',
    position: 'relative',
  },
  progressFill: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 8,
  },
  progressUnfilled: {
    height: '100%',
    backgroundColor: colors.honeydew,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: 8,
    minWidth: 40,
  },
  progressPercentage: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.honeydew,
    fontWeight: '600',
  },
  progressTarget: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.fenceGreen,
    fontWeight: '600',
    lineHeight: 12,
  },
  progressStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  progressStatusText: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 6,
    opacity: 0.8,
  },
  scrollableContent: {
    flex: 1,
    paddingTop: 380,
  },
  contentBackground: {
    flex: 1,
    backgroundColor: colors.honeydew,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: 20,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  monthHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginTop: 24,
    marginBottom: 16,
  },
  monthHeader: {
    ...typography.titleBold,
    fontSize: 24,
    color: colors.void,
    fontWeight: 'bold',
  },
  seeAllText: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.void,
    fontWeight: '500',
  },
  transactionsContainer: {
    paddingHorizontal: 24,
  },
  transactionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGreen,
  },
  transactionIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.lightBlue,
    opacity: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  transactionDetails: {
    flex: 1,
  },
  transactionName: {
    ...typography.bodyLarge,
    fontSize: 16,
    color: colors.void,
    fontWeight: '600',
    marginBottom: 4,
  },
  transactionMeta: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.vividBlue,
    opacity: 0.8,
    marginBottom: 2,
  },
  transactionCategory: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.cyprus,
    opacity: 0.8,
  },
  transactionAmountPositive: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
  },
  transactionAmountNegative: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
})

