import { StyleSheet } from 'react-native'
import { colors, typography } from '../../utils/globalStyle'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.honeydew,
    width: '100%',
  },
  headerSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.caribbeanGreen,
    width: '100%',
    height: '100%',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerContent: {
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  headerTitle: {
    ...typography.titleBold,
    fontSize: 20,
    color: colors.void,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  bellButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryCard: {
    backgroundColor: colors.caribbeanGreen,
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 24,
    marginTop: 20,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    height: 160,
    elevation: 3,
  },
  summaryItem: {
    flex: 1,
  },
  progressContainerWrapper: {
    alignItems: 'center',
    marginBottom: 12,
  },
  circularProgressOuter: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 8,
    overflow: 'hidden',
  },
  progressArcContainer: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  progressArc1: {
    position: 'absolute',
    width: 76,
    height: 76,
    borderRadius: 38,
    borderWidth: 4,
    borderColor: colors.caribbeanGreen,
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
    transform: [{ rotate: '-45deg' }],
    top: 0,
    left: 0,
  },
  progressArc2: {
    position: 'absolute',
    width: 76,
    height: 38,
    backgroundColor: colors.caribbeanGreen,
    top: 0,
    left: 0,
    borderTopLeftRadius: 38,
    borderTopRightRadius: 38,
  },
  circularProgressInner: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    zIndex: 1,
  },
  savingsTextContainer: {
    alignItems: 'center',
    marginTop: -15
  },
  savingsTextLine1: {
    ...typography.bodyMedium,
    fontSize: 12,
    color: colors.void,
    fontWeight: '500',
  },
  savingsTextLine2: {
    ...typography.bodyMedium,
    fontSize: 12,
    color: colors.void,
    fontWeight: '500',
  },
  summaryLabelWhite: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.void,
    fontWeight: '400',
  },
  summaryDivider: {
    width: 1,
    height: 200,
    backgroundColor: colors.caribbeanGreen,
    opacity: 0.3,
    marginHorizontal: 16,
    marginTop: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  summaryRowDivider: {
    width: '80%',
    height: 1,
    backgroundColor: colors.caribbeanGreen,
    opacity: 0.3,
    marginLeft: 32,
  },
  summaryDetails: {
    marginLeft: 12,
    flex: 1,
  },
  summaryAmountWhite: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
    marginTop: 4,
  },
  summaryAmountBlue: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.oceanBlue,
    fontWeight: 'bold',
    marginTop: 4,
  },
  financialSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  balanceContainer: {
    flex: 1,
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  balanceLabel: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 4,
    opacity: 0.8,
  },
  balanceAmount: {
    ...typography.titleBold,
    fontSize: 22,
    color: colors.honeydew,
    fontWeight: 'bold',
  },
  divider: {
    width: 1,
    backgroundColor: colors.caribbeanGreen,
    opacity: 0.2,
    marginHorizontal: 16,
  },
  expenseContainer: {
    flex: 1,
    alignItems: 'flex-end',
  },
  expenseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  expenseLabel: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 4,
    opacity: 0.8,
  },
  expenseAmount: {
    ...typography.titleBold,
    fontSize: 22,
    color: colors.oceanBlue,
    fontWeight: 'bold',
  },
  progressContainer: {
    marginBottom: 12,
  },
  progressBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressBar: {
    flex: 1,
    height: 27,
    backgroundColor: colors.void,
    borderRadius: 24,
    overflow: 'hidden',
    flexDirection: 'row',
    position: 'relative',
  },
  progressFill: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 8,
  },
  progressUnfilled: {
    height: '100%',
    backgroundColor: colors.honeydew,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'flex-end',
    paddingRight: 8,
    minWidth: 40,
  },
  progressPercentage: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.honeydew,
    fontWeight: '600',
  },
  progressTarget: {
    ...typography.bodySmall,
    fontSize: 10,
    color: colors.fenceGreen,
    fontWeight: '600',
    lineHeight: 12,
  },
  progressStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  progressStatusText: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.void,
    marginLeft: 6,
    opacity: 0.8,
  },
  cardsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  incomeCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 2,
    borderColor: colors.lightBlue,
    alignItems: 'center',
  },
  expenseCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 14,
    borderWidth: 2,
    borderColor: colors.lightBlue,
    alignItems: 'center',
  },
  cardIcon: {
    marginBottom: 8,
  },
  cardLabel: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.cyprus,
    marginBottom: 8,
    fontWeight: '500',
  },
  cardAmount: {
    ...typography.titleBold,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
  },
  cardAmountExpense: {
    ...typography.titleBold,
    fontSize: 18,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
  scrollableContent: {
    flex: 1,
    paddingTop: 380,
  },
  contentBackground: {
    flex: 1,
    backgroundColor: colors.honeydew,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: 16,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  transactionsTitle: {
    ...typography.titleBold,
    fontSize: 18,
    color: colors.void,
    fontWeight: 'bold',
  },
  seeAllText: {
    ...typography.bodyMedium,
    fontSize: 14,
    color: colors.void,
    fontWeight: '500',
  },
  transactionsContainer: {
    paddingHorizontal: 20,
  },
  transactionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGreen,
  },
  transactionIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.lightBlue,
    opacity: 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  transactionDetails: {
    flex: 1,
  },
  transactionName: {
    ...typography.bodyLarge,
    fontSize: 14,
    color: colors.void,
    fontWeight: '600',
    marginBottom: 2,
  },
  transactionMeta: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.vividBlue,
    opacity: 0.8,
    marginBottom: 2,
  },
  transactionCategory: {
    ...typography.bodySmall,
    fontSize: 12,
    color: colors.cyprus,
    opacity: 0.8,
  },
  transactionAmountPositive: {
    ...typography.heading4,
    fontSize: 18,
    color: colors.caribbeanGreen,
    fontWeight: 'bold',
  },
  transactionAmountBlue: {
    ...typography.heading4,
    fontSize: 16,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
  transactionAmountNegative: {
    ...typography.heading4,
    fontSize: 16,
    color: colors.vividBlue,
    fontWeight: 'bold',
  },
})

